FROM apache/airflow:3.2.0

USER root
RUN apt-get update && apt-get install -y gnupg2 curl ca-certificates \
    && curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > /usr/share/keyrings/microsoft-archive-keyring.gpg \
    && curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev

USER airflow
RUN pip install pandas requests sqlalchemy pyodbc scikit-learn